# Introduction {.unnumbered}

Hello! My name is Yihan Li and I'm from Chengdu, a city in Southwest China renowned for its pandas and hotpot. During my undergraduate studies in Urban Management at the University of Electronic Science and Technology of China, I developed a keen interest in courses like Data Mining, Principles and Applications of Artificial Intelligence, and GIS. This interest sparked my passion for applying these practical skills to solve real-world problems, even leading me to view smart cities as a promising direction for urban development. Fortuitously, I'm currently pursuing an MSc in Urban Spatial Science at CASA, which I was dreamed of .

Although I had some exposure to related courses previously, my knowledge was not in-depth. This master's program represented an opportunity for me to enhance my skills in geospatial analysis and coding. This week marks potentially my last to take courses as a student, cause in the latter half of this year, I will embark on a job search. I'm deeply grateful for the invaluable experiences and skills I've gained here. I aspire to apply the knowledge acquired to the development of my hometown.

This website serves as a learning diary for my module, Remotely Sensing Cities and Environments, where I document my thoughts and learning journey. I have learned fundamentals about remote sensing, and also had a deeper understanding about some related applications and practicals. I hope that you enjoy it!
